### ISSUE TITLE
What if plural = singular ?

### ISSUE THREAD

**Issue by qbonnard** [dhyegofernando/activerecord_humanized_enum#1]
First of all, thanks a lot for sharing this, it is exactly what I needed (along with the active_admin gem) to automagically translate enums :)

## Description

If `enum.pluralize == enum`, there is no way to provide translations (unless I missed something)

## How to reproduce

Define `enum species: [:tiger, :whale]`

## What do you expect

Being able to provide a translation fo :salmon and :gold_fish, maybe with something like
```
fr:
  activerecord:
    attributes:
      animal:
        species: Espèce
        species/values:
          tiger: Tigre
          whale: Baleine
```

## What happened instead

Because 'species'.pluralize == 'species', the enum's values and name collide
```
fr:
  activerecord:
    attributes:
      animal:
        species: Espèce
        species:
          tiger: Tigre
          whale: Baleine
```

I hack around that by adding into `config/initializers/inflections.rb`
```
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'species', 'speciesPL'
end
```
but it does not seem like a good idea...

## Gem version:

Version: 0.1.2
